services:
  api:
    image: bjsoftware/rfb-api:latest
    networks:
      - network_db
      - network_public
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-rfb_user}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME:-dados_rfb}
      DB_SISTEMA_NAME: ${DB_SISTEMA_NAME:-buscadados}
      DB_VIACEP_NAME: ${DB_VIACEP_NAME:-dados_viacep}
      ADMIN_KEY: ${ADMIN_KEY}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ETL_DOWNLOAD_DIR: /var/lib/etl/download
      ETL_EXTRACT_DIR: /var/lib/etl/extraidos
    volumes:
      - etl_downloads:/var/lib/etl/download
      - etl_extraidos:/var/lib/etl/extraidos
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.swarm.network=network_public
        - traefik.http.routers.rfb-api.rule=Host(`api.buscadados.bjsoft.com.br`)
        - traefik.http.routers.rfb-api.entrypoints=websecure
        - traefik.http.routers.rfb-api.tls=true
        - traefik.http.routers.rfb-api.tls.certresolver=letsencryptresolver
        - traefik.http.services.rfb-api.loadbalancer.server.port=3001

  frontend:
    image: bjsoftware/rfb-frontend:latest
    networks:
      - network_public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      labels:
        - traefik.enable=true
        - traefik.swarm.network=network_public
        - traefik.http.routers.rfb-frontend.rule=Host(`buscadados.bjsoft.com.br`)
        - traefik.http.routers.rfb-frontend.entrypoints=websecure
        - traefik.http.routers.rfb-frontend.tls=true
        - traefik.http.routers.rfb-frontend.tls.certresolver=letsencryptresolver
        - traefik.http.services.rfb-frontend.loadbalancer.server.port=80

networks:
  network_db:
    external: true
  network_public:
    external: true

volumes:
  etl_downloads:
  etl_extraidos:
